### ISSUE TITLE
What are repositories?

### ISSUE THREAD

**Issue by ferdinandsalis** [vitaly-t/pg-promise-demo#1]
Hi there,

I am new to databases and I am curious what is the meaning of repository in the context of databases and this demo. Searching on google does not render sufficient understandable information ☺️.

Thanks!

**Comment by vitaly-t** [comment]
It was discussed here: https://github.com/vitaly-t/pg-promise/issues/98

**Comment by ferdinandsalis** [comment]
@vitaly-t thanks for the quick reply!

**Comment by vitaly-t** [comment]
It all boils down to these links:
- https://msdn.microsoft.com/en-us/library/ff649690.aspx
- http://stackoverflow.com/questions/11985736/repository-pattern-step-by-step-explanation

You are welcome!
