### ISSUE TITLE
Connection release

### ISSUE THREAD

**Issue by it2ak** [vitaly-t/pg-promise-demo#10]
HI Vitaliy, First of all, I highly appreciate your work with the great library.
I have used this demo to build our solution but I did not find any done() methods to release connections in the demo.
Is it needed not 'no-tasks' queries?
In documentation, it is mentioned that connections are release for 'task' methods but I did not find any details for 'no-tasks'.

**Comment by vitaly-t** [comment]
It is not needed. Connections are managed automatically.
