### ISSUE TITLE
Can not compile TypeScript using tsconfig.json

### ISSUE THREAD

**Issue by volodalexey** [vitaly-t/pg-promise-demo#11]
Initial tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true
  }
}
```
And I get a bunch of errors in TS compiler.
However one error that I can not avoid:
```
node_modules/pg-promise/typescript/pg-promise.d.ts:14:27 - error TS2497: Module '"/...project folder.../node_modules/pg-promise/typescript/ext-promise"' resolves to a non-module entity and cannot be imported using this construct.

14 import * as XPromise from './ext-promise'; // External Promise Provider
                             ~~~~~~~~~~~~~~~
```
Because of this Error I must copy all these files into `src` and modify this
`import * as XPromise from './ext-promise';` to this `import XPromise = require('./ext-promise');`

Can I avoid this error without modifying your source code?

**Comment by vitaly-t** [comment]
@volodalexey That's the problem with your `"esModuleInterop": true`. If you remove it, it should just work fine. Why do you need in the first place?

**Comment by volodalexey** [comment]
@vitaly-t I am not expirienced TypeScript programmer, that is why I am using "default" TS config after `tsc ---init` in `v3.0.0`. Ok. With `"esModuleInterop": false` - I do not see any errors. Thanks.

**Comment by vitaly-t** [comment]
`esModuleInterop` was added for some Babel compatibility: https://www.typescriptlang.org/docs/handbook/compiler-options.html

Not sure if anything needs to be done about it, or just not use it ;)
