### ISSUE TITLE
What is the best solution for many to many relationship

### ISSUE THREAD

**Issue by danylkaaa** [vitaly-t/pg-promise-demo#12]
Could you show me a project structure, according to provided in this repository, which allows me to realize many-to-may relationship? Should I create an allotted repo for UserProduct or I should try to implement the logic of creation additional table in user or product class?
I mean, should the project structure looks like bellow:
```
/db/repos/user
/db/repos/product
/db/repose/userProduct
```

**Comment by vitaly-t** [comment]
The repository pattern shown here reflects the entities structure in your database. What you are asking is the business level, which is a level up, and it is up to you how you implement it.

For example, your `product` repository can implement method `getForUser(userId: string)`, or you can have repository `user` implement method `getProducts()`. It is up to you, and the business requirements for the operations are supposed to dictate the best approach.

And again, you decide whether or not implement a separate `userProduct` repository, based on the business requirements.
