### ISSUE TITLE
[TypeScript] Cannot invoke an expression whose type lacks a call signature!!!

### ISSUE THREAD

**Issue by AhmedBHameed** [vitaly-t/pg-promise-demo#13]
By using the same example on your repo. here
https://github.com/vitaly-t/pg-promise-demo/blob/master/TypeScript/db/index.ts

I'm getting this Typescript error saying: `[ts] Cannot invoke an expression whose type lacks a call signature. Type 'typeof pgPromise' has no compatible call signatures. [2349]` !!!

```typescript
import { IMain, IDatabase, IOptions } from "pg-promise";
import * as pgPromise from "pg-promise";

const pgp: IMain = pgPromise(); // Error pop up here!!
```

Using ES6 in `tsconfig.json`

Any idea?

**Comment by vitaly-t** [comment]
What version of TypeScript are you using?

Must be something unique, because nobody else has that problem.

**Comment by AhmedBHameed** [comment]
Hi @vitaly-t, Thank you for this lovely library. so the version is `Version 3.2.2`.
I fallback to `require` just to override this issue. But still wondering why is not accepted by typescript !!

Extra to that this is my **tsconfig.json** file

```json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "lib": ["es2015", "dom"],
    "sourceMap": true,
    "outDir": "./dist",
    "removeComments": true,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "moduleResolution": "node",
    "baseUrl": ".",
    "paths": {
      "*": ["node_modules/*", "src/Types/*"]
    },
    "esModuleInterop": true
  },
  "include": ["src/**/*"]
}
```

Thank you.

**Comment by vitaly-t** [comment]
I've seen this `"esModuleInterop": true` causing problems in the past. Try removing it ;)

Anyhow, pg-promise builds fine with the default settings, it is something in your custom config that breaks.

**Comment by AhmedBHameed** [comment]
That solved my problem. Thank you.

**Comment by EvanCarroll** [comment]
just do 

    import pgPromise from "pg-promise";

Otherwise you'll have to do `pgPromise.pgPromise`

**Comment by vitaly-t** [comment]
This is standard TypeScript configuration flag - `esModuleInterop`. When set to true, the import syntax is `import pgPromise from 'pg-promise'`, and when `false`, which is the default, the syntax is `import * as pgPromise from 'pg-promise'`.

The library simply gives you example of what is the default TypeScript configuration.
