### ISSUE TITLE
ParameterizedQuery example in the QueryFile?

### ISSUE THREAD

**Issue by EvanCarroll** [vitaly-t/pg-promise-demo#14]
You have an example in the query file using what looks like es6 placeholders. It would be great to see that explained in the comments or otherwise. It would also be great to have a ParameterizedQuery example added.

**Comment by vitaly-t** [comment]
If you are talking about external SQL files, those are not ES6 placeholders, they are variables as supported by the library, see [Named Parameters](https://github.com/vitaly-t/pg-promise#named-parameters).
