### ISSUE TITLE
Do not however reuse any of the HTTP-service code

### ISSUE THREAD

**Issue by osseonews** [vitaly-t/pg-promise-demo#19]
Can you please explain what mean by: "Do not however reuse any of the HTTP-service code, it is over-simplified, for the test, not for you to copy."

We were thinking of using this demo as a type skeleton for our DB project, and were not clear what you meant about the http-service code. Thanks.

**Comment by vitaly-t** [comment]
Why didn't you quote [the whole thing](https://github.com/vitaly-t/pg-promise-demo/blob/master/TypeScript/index.ts#L4)? It explains it to you right there...

```js
/////////////////////////////////////////////////////////////////////////////
// IMPORTANT:
//
// Do not re-use the HTTP-service part of the code from here!
// It is an over-simplified HTTP service with just GET handlers, because:
//
// 1. This demo is to be tested by typing URL-s manually in the browser;
// 2. The focus here is on a proper database layer only, not an HTTP service.
/////////////////////////////////////////////////////////////////////////////
```
