### ISSUE TITLE
Return a result from select command

### ISSUE THREAD

**Issue by ghost** [vitaly-t/pg-promise-demo#2]
Greetings,

I've followed your instructions on how to properly separate our structure using `pg-promise`, and everything's working fine. I'm building a Slack slash commands using it, and when selecting data from database, I need it to display something like `[username] is [status]`. Following other operation's example, I suppose it would be something like this:

```
select: () =>
    rep.any('SELECT username, status, emoji FROM ' + table)
    .then(res => ?),
```

But I cannot access these columns nor I have found examples of such. Is it possible to be done?

Thank you.

**Comment by vitaly-t** [comment]
> But I cannot access these columns nor I have found examples of such

See the method's [API](http://vitaly-t.github.io/pg-promise/Database.html#.any) and the [examples](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example). If you don't understand the basics of how to use promises, that's another question.

**Comment by ghost** [comment]
Maybe what I am trying to accomplish is made differently.

The code `select: () => rep.any('SELECT username, status, emoji FROM status')` returns `[{"username":"gabrielmf","status":"OUT","emoji":"runner"}]` on Slack channel. What I intended to do was to, instead of display the result like this, to display it in a better way, like this:

> gabrielmf is OUT :runner: 
> anotheruser is HUNRY :spaghetti: 
> ...

I tried to follow the examples of the other operations and to use `db.each`. By adding `.then(data => data)` after the snipped above, it returned the same result it does now without it, and nothing was returned when accessing, for example, `data.username`.

**Comment by vitaly-t** [comment]
Something like this?

``` js
db.map('SELECT username, status, emoji FROM $1~', table, row=> {
    return row.username + ' is ' + row.status;
})
    .then(data=> {
        // data;
    })
    .catch(error=> {
        // error;
    });
```

**Comment by ghost** [comment]
I see, so there's where you put it. Other examples I did is like this:

```
insert: values =>
        rep.one(sql.insert, values)
        .then(res => 'Your status has been updated to ' + values.status)
```

Thank you, it has solved it.

**Comment by vitaly-t** [comment]
Perhaps `+ res.status`, and not `+ values.status`?

**Comment by ghost** [comment]
Yes, sure. What I meant is that I've put the message in `.then`.
