### ISSUE TITLE
Complex transactions example

### ISSUE THREAD

**Issue by stojkoskih** [vitaly-t/pg-promise-demo#20]
Could you please show an example on how to handle more complex transactions using pgp that may contain a bit of "business logic" in it.

**Comment by vitaly-t** [comment]
This library is built on promises, so any complex complex business logic would be built on promises as well. If you have a specific question, then ask it. Otherwise, your question is too broad.

**Comment by stojkoskih** [comment]
Say for example we have a transaction like this:
```
db.tx(async t=>{
    const age = await t.one('select age from users where id=$1', id);
    if (age>=18){
        await t.none('update users set canVote=true where id=$1', id);
    }else {
        //do nothing
    }
})
```
Can you have this kind of logic inside of a tx function and if so how does this translate in to SQL considering it has conditions inside?

**Comment by vitaly-t** [comment]
That's a normal transaction logic, nothing complex about it :)

> how does this translate in to SQL considering it has conditions inside

The condition is a the JavaScript-specific, it has nothing to do with the SQL logic. And to see the actual SQL being executed, use either use [pg-monitor], or at least event [query].

Also, you do not need to use this:

```js
else {
        //do nothing
    }
```

In fact, such a transaction would be just:

```js
await db.tx(async t => {
    const age = await t.one('select age from users where id = $1', id);
    if (age >= 18) {     
        return t.none('update users set canVote = true where id = $1', id);
        // or you can do just "await" here, makes no real difference in this case.
    }
})
```

[pg-monitor]:https://github.com/vitaly-t/pg-monitor
[query]:https://vitaly-t.github.io/pg-promise/global.html#event:query

**Comment by stojkoskih** [comment]
Thank you, this point in the right direction is what I needed!

**Comment by vitaly-t** [comment]
n.p. :)
