### ISSUE TITLE
${userId} in .SQL file 

### ISSUE THREAD

**Issue by josephtey** [vitaly-t/pg-promise-demo#22]
Trying to map values as query parameters, but running into this issue: 

`error: syntax error at or near "$"`

SQL file looks like this:

`INSERT INTO products (user_id, name)
VALUES(${userId}, ${productName})
RETURNING *
`

VSCode is also picking up the `${userId}` as a syntax error... how do I fix this?

**Comment by vitaly-t** [comment]
If the query is inside SQL file, then how are you getting `syntax error at or near "$"` error?

It is certainly not an error produced by the library.

**Comment by josephtey** [comment]
Ah my bad, had an MYSQL extension installed in VSCode :/
