### ISSUE TITLE
Example and help are confusing is PGP -> DC ? 

### ISSUE THREAD

**Issue by nicewaytodoit** [vitaly-t/pg-promise-demo#24]
In following line:
https://github.com/vitaly-t/pg-promise-demo/blob/e768bd29452e4f0b4abc3499ceb8d9ab90ca4d2c/JavaScript/db/index.js#L20

pgp is used, in Objects initialization, but "pgp" is later initialized with:

```
const initOptions = {
   promiseLib: promise,
    extend(obj, dc) {
        obj.users = new Users(obj, pgp);
        obj.products = new Products(obj, pgp);
    }
};

// Initializing the library:
const pgp = pgPromise(initOptions);    //// ??? pgp needs initOptions ... and initOptions extends uses pgp which is initialized below? 

// Creating the database instance:
const db = pgp(dbConfig);
```

pgp needs initOptions ... and initOptions extends uses pgp which is initialized below?

**Comment by vitaly-t** [comment]
`extend` is called after `pgp` is set, when creating the database instance. Otherwise, it wouldn't work.

```js
const db = pgp(dbConfig); // at this point `extend` will be called
```

because we are extending the database object.
