### ISSUE TITLE
ISSUE REGARDING INSERTION OF STRING IN POSTGRES QUERY

### ISSUE THREAD

**Issue by AryamannTomar** [vitaly-t/pg-promise-demo#25]
Hi @vitaly-t! I have a doubt in the code given below.
I have 2 functions  => createTable and createTable2
When I use them as => 
db.users.createTable2({appid: '123'});    =>  WORKS
But db.users.createTable({appid: '123'}); => DOESNT WORK 

I want my db.users.createTable to also work 
createTable.sql  has the query    =>    `CREATE TABLE tbl_${appid}(dt date, txt text);`

[ CODE INSIDE THE USERS.ts FILE is ]
`import {IDatabase, IMain} from 'pg-promise';
import {IResult} from 'pg-promise/typescript/pg-subset';
import {users as sql} from '../sql';
export class UsersRepository {
    constructor(private db: IDatabase<any>, private pgp: IMain) {
    }
    
    async createTable(values: {appid: string}): Promise<null> {
        return this.db.none(sql.createTable, {
            appid: values.appid
        });
    }

    async createTable2(values: {appid: string}): Promise<null> {
        return this.db.none(sql.createTable, {
            appid: +values.appid
        });
    }
}`

The postgreSQL query which is being executed is `CREATE TABLE tbl_'123'(dt date, txt text);`   =>  I dont Want to add apostrophe outside my `${appid}` variable. 

Can you please help me?

**Comment by AryamannTomar** [comment]
my createTable.sql query is  create table tbl_${appid}(dt date, txt text); 
I want      db.users.createTable({appid: '123abc'});  to work   =>  To Pass a string Literal with no apostrophe in my postgres query
But currently it queries in postgreSQL like =>  create table tbl_'123abc'(dt date, txt text);  which is giving me an error

**Comment by vitaly-t** [comment]
I do not see from your code why the second one wouldn't work. If you still have the issue, it must be elsewhere.

Those are just two separate class methods.

**Comment by vitaly-t** [comment]
Closing, as it must be a dead issue now.

**Comment by tarunanand-dev** [comment]
Yes, this was resolved. Thank you for your suggestion.
