### ISSUE TITLE
many to many examples

### ISSUE THREAD

**Issue by Mikou** [vitaly-t/pg-promise-demo#4]
I would find it useful with more advanced examples involving many-to-many relations.

**Comment by vitaly-t** [comment]
Can't cover everything in a simple demo.

You can start with this: http://stackoverflow.com/questions/36586486/best-way-to-query-a-many-to-many-relationship-using-pg-promise

Then follow the logic, it is just generic many-to-many SQL, plus generic promise approach, nothing special.
