### ISSUE TITLE
question regarding new repo structure

### ISSUE THREAD

**Issue by kissmygritts** [vitaly-t/pg-promise-demo#7]
In previous versions of the repo, `db\repos` looked looked like this:

``` javascript
var sql = require('../sql').products

module.exports = rep => {
  create: () => rep.none(sql.create),
  drop: () => rep.none(sql.drop)
}
```

Now you've changed it to use classes.

``` javascript
const sql = require('../sql').products;

class ProductsRepository {
    constructor(db, pgp) {
        this.db = db;
        this.pgp = pgp;
    }

    create() {
        return this.db.none(sql.create);
    }

    drop() {
        return this.db.none(sql.drop);
    }
}
```
I'm curious as to why you've made this change for the demo? Thanks for the input.

**Comment by vitaly-t** [comment]
Because the library was supporting legacy Node.js 0.10 and 0.12 till version 5.6.0 when it was removed, requiring Node 4.x from thence.

Following it, the demo was refactored for ES6 syntax, though the new and old code work the same.

**Comment by kissmygritts** [comment]
Thank you.
